name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  

    - name: Publish Blazor WebAssembly
      run: dotnet publish Terjeki.Scheduler.Web/Terjeki.Scheduler.Web.csproj -c Release -o release

    - name: Change base href for GitHub Pages
      run: sed -i 's|<base href="/" />|<base href="/Terjeki.Scheduler/" />|' release/wwwroot/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
