name: Build & Deploy API via GHCR

on:
  push:
    branches: [ "developer" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./Terjeki.Scheduler.Web
          file: ./Terjeki.Scheduler.Web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/terjeki-scheduler-api:${{ github.sha }}

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}     
          app: api                                    
          token: ${{ secrets.CAPROVER_APP_TOKEN }}   
          image: ghcr.io/${{ github.repository_owner }}/terjeki-scheduler-api:${{ github.sha }}
